spring:
  application:
    name: spring-board

  datasource:
    url: jdbc:postgresql://localhost:5432/example
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
jwt:
  secret: your_secret_key