name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        shell: bash
        run: |
          echo "HOME is $HOME"
          ls -ld $HOME
          mkdir -p $HOME/.ssh
          chmod 700 $HOME/.ssh
          printf "%s" "${{ secrets.KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> $HOME/.ssh/known_hosts || true

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            cd /home/ubuntu/spring_board_crud  # 실제 EC2의 경로로 변경
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF